### ISSUE TITLE
The tag 'meta name=viewport' appears more than once in the document.

### ISSUE THREAD

**Issue by IvanPr** [MohammedKaludi/ampforwp-custom-theme#10]
The tag 'meta name=viewport' appears more than once in the document.
http://i.imgur.com/DcgeBG6.png

There is no need for the 
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
in single.php

**Comment by MohammedKaludi** [comment]
Yes, this is the known issue already reported by some other user, the issue came after we added meta name=viewport from the hook in AMPforWP plugin, and all the direct instances need to be removed.

I will fix it very soon in this one as well.

**Comment by IvanPr** [comment]
Great.
