### ISSUE TITLE
Fatal error caused by Essential Addons Post_Carousel not found in amp-post-carousel.php

### ISSUE THREAD

**Issue by nisiwi** [MohammedKaludi/ampforwp-custom-theme#19]
Fatal error - result from WP in debbg mode.

Fatal error: Trait 'Essential_Addons_Elementor\Pro\Template\Content\Post_Carousel' not found in /home/ACCOUNT/public_html/wp-content/plugins/amp-pagebuilder-compatibility/widgets/essential-addon/amp-post-carousel.php on line 18

WP version = 5.5.1
AMPforWP version = 1.0.64.1 and PageBuilder Compatibility version = 1.9.47.1
Essential Addons Pro version = 4.2.0

Apologies if this is a duplicate post.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4779
