### ISSUE TITLE
AMP Starter Theme and Design 3

### ISSUE THREAD

**Issue by IvanPr** [MohammedKaludi/ampforwp-custom-theme#7]
AMP Starter Theme shows up only when Design 3 is selected.
With Design 1 and 2 only header shows up...

The html code end with:
<b>Fatal error</b>:  Class 'AMPforWP_Menu_Walker' not found in <b>\www\blog\wp-content\plugins\ampforwp-custom-theme-master\template\header-bar.php</b> on line <b>53</b><br />

**Comment by MohammedKaludi** [comment]
Hmmm... Thank you for reporting, I will check it once and add the fix very soon.

Thank you for reporting,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
Hey @IvanPr,

I have fixed this in the latest commit. If you have any other question, please feel free to ask.

Thank you,
Mohammed Kaludi

**Comment by IvanPr** [comment]
Thank you @MohammedKaludi 
The issue was fixed indeed.
