### ISSUE TITLE
 Class 'AMPforWP_Menu_Walker' not found error

### ISSUE THREAD

**Issue by mommaroodles** [MohammedKaludi/ampforwp-custom-theme#8]
After install the theme, I got this error message when viewing the amp page

Fatal error: Class 'AMPforWP_Menu_Walker' not found in /../../../wp-content/plugins/ampforwp-custom-theme-master/template/header-bar.php on line 53

I've also got the AMP validator extension in Chrome and it says the following: 

The tag 'meta name=viewport' appears more than once in the document.

**Comment by MohammedKaludi** [comment]
@mommaroodles Thank you for reporting the issue. This issue was reported a few days ago by another user as well https://github.com/MohammedKaludi/ampforwp-custom-theme/issues/7

I'm planning to look into the issue by today and will get back to you.

Thank you,
Mohammed Kaludi

**Comment by rkumarat** [comment]
Hey Mohammed,

I have installed it and got the same error. Can you please figure it out, what it could be?

Best
Raman

**Comment by MohammedKaludi** [comment]
Hey @mommaroodles and @rkumarat 

I have fixed this in the latest commit.

If you have any other question, please feel free to ask.

Thank you,
Mohammed Kaludi

**Comment by mommaroodles** [comment]
:) Ahh thank you - will take a look and let you know - thank you so much - thumbs up!

**Comment by rkumarat** [comment]
Thanks Mohammed very much, will check it.
